// Package telemetry forwards testkit's telemetry-service domain (P6) to the
// embedded telemetry-service module. Messages mirror the downstream proto 1:1,
// so every converter below is a field-identical copy (enums int-cast,
// sub-messages recursive). Regenerated by /tmp/gen_forward.py.
package telemetry

import (
	"context"
	telemetryv1 "github.com/servekit/api/gen/go/telemetry/v1"

	dnv1 "github.com/servekit/api/gen/go/telemetry/v1"
	testkitv1 "github.com/servekit/api/gen/go/testkit/v1"
	telemetryservice "github.com/servekit/telemetry-service/pkg"
	"google.golang.org/grpc/metadata"
)

// Service holds the telemetry-service client (module or grpc mode — the
// pkg.Service interface covers both).
type Service struct {
	client telemetryservice.Service
	// adminToken is forwarded as `Authorization: Bearer <token>`
	// metadata on admin-surface RPCs (telemetry-service guards them;
	// license-service has no guard today — empty token is a no-op).
	adminToken string
}

// Option customizes the telemetry domain service.
type Option func(*Service)

// New builds the telemetry domain service.
func New(client telemetryservice.Service, adminToken string, opts ...Option) *Service {
	s := &Service{client: client, adminToken: adminToken}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// Backend returns the raw telemetry-service handle (module or gRPC mode).
// Used by pkg/server.go to mount the raw ingestion HTTP face
// (telemetry's pkg/ingesthttp), which speaks the downstream proto types
// directly and must not be adapted through testkit's mirrored messages.
func (s *Service) Backend() telemetryservice.Service { return s.client }

// adminCtx appends the admin Bearer token to the outgoing metadata.
func (s *Service) adminCtx(ctx context.Context) context.Context {
	if s.adminToken == "" {
		return ctx
	}
	return metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+s.adminToken)
}
func (s *Service) Ingest(ctx context.Context, req *testkitv1.IngestRequest) (*testkitv1.IngestResponse, error) {
	resp, err := s.client.Ingest(ctx, toDnIngestRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitIngestResponse(resp), nil
}

func (s *Service) CreateTenantConfig(ctx context.Context, req *testkitv1.CreateTenantConfigRequest) (*testkitv1.CreateTenantConfigResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.CreateTenantConfig(ctx, toDnCreateTenantConfigRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitCreateTenantConfigResponse(resp), nil
}

func (s *Service) GetTenantConfig(ctx context.Context, req *testkitv1.GetTenantConfigRequest) (*testkitv1.GetTenantConfigResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.GetTenantConfig(ctx, toDnGetTenantConfigRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitGetTenantConfigResponse(resp), nil
}

func (s *Service) UpdateTenantConfig(ctx context.Context, req *testkitv1.UpdateTenantConfigRequest) (*testkitv1.UpdateTenantConfigResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.UpdateTenantConfig(ctx, toDnUpdateTenantConfigRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitUpdateTenantConfigResponse(resp), nil
}

// ListApps lists every app (types imported across domains like the storage/
// message app forwards — no mirrored DTO, no converters).
func (s *Service) ListTenantConfigs(ctx context.Context, req *telemetryv1.ListTenantConfigsRequest) (*telemetryv1.ListTenantConfigsResponse, error) {
	return s.client.ListTenantConfigs(s.adminCtx(ctx), req)
}

// RotateAppSecret mints a new business-identity credential (ak/sk pair).
func (s *Service) RotateTenantConfigSecret(ctx context.Context, req *telemetryv1.RotateTenantConfigSecretRequest) (*telemetryv1.RotateTenantConfigSecretResponse, error) {
	return s.client.RotateTenantConfigSecret(s.adminCtx(ctx), req)
}

func (s *Service) RotateToken(ctx context.Context, req *testkitv1.RotateTokenRequest) (*testkitv1.RotateTokenResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.RotateToken(ctx, toDnRotateTokenRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitRotateTokenResponse(resp), nil
}

func (s *Service) RevokeToken(ctx context.Context, req *testkitv1.RevokeTokenRequest) (*testkitv1.RevokeTokenResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.RevokeToken(ctx, toDnRevokeTokenRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitRevokeTokenResponse(resp), nil
}

func (s *Service) CreateSigningKey(ctx context.Context, req *testkitv1.CreateSigningKeyRequest) (*testkitv1.CreateSigningKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.CreateSigningKey(ctx, toDnCreateSigningKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitCreateSigningKeyResponse(resp), nil
}

func (s *Service) RevokeSigningKey(ctx context.Context, req *testkitv1.RevokeSigningKeyRequest) (*testkitv1.RevokeSigningKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.RevokeSigningKey(ctx, toDnRevokeSigningKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitRevokeSigningKeyResponse(resp), nil
}

func (s *Service) ReplaceEventRules(ctx context.Context, req *testkitv1.ReplaceEventRulesRequest) (*testkitv1.ReplaceEventRulesResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ReplaceEventRules(ctx, toDnReplaceEventRulesRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitReplaceEventRulesResponse(resp), nil
}

func (s *Service) SetVersionBlocked(ctx context.Context, req *testkitv1.SetVersionBlockedRequest) (*testkitv1.SetVersionBlockedResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.SetVersionBlocked(ctx, toDnSetVersionBlockedRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitSetVersionBlockedResponse(resp), nil
}

func (s *Service) GetTenantConfigStats(ctx context.Context, req *testkitv1.GetTenantConfigStatsRequest) (*testkitv1.GetTenantConfigStatsResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.GetTenantConfigStats(ctx, toDnGetTenantConfigStatsRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitGetTenantConfigStatsResponse(resp), nil
}

func toDnTenantConfig(src *testkitv1.TenantConfig) *dnv1.TenantConfig {
	if src == nil {
		return nil
	}
	out := &dnv1.TenantConfig{}
	out.Id = src.Id
	out.AppKey = src.AppKey
	out.TenantKey = src.TenantKey
	out.Name = src.Name
	out.Email = src.Email
	out.StrictVersions = src.StrictVersions
	out.AuthMode = dnv1.AuthMode(src.AuthMode)
	out.AuthGraceUntil = src.AuthGraceUntil
	out.RatePerMinute = src.RatePerMinute
	out.RatePerDay = src.RatePerDay
	out.RawRetentionDays = src.RawRetentionDays
	out.DailyEventBudget = src.DailyEventBudget
	out.Disabled = src.Disabled
	out.AppSecret = src.AppSecret
	out.CreatedAt = src.CreatedAt
	out.UpdatedAt = src.UpdatedAt
	return out
}

func toTestkitTenantConfig(src *dnv1.TenantConfig) *testkitv1.TenantConfig {
	if src == nil {
		return nil
	}
	out := &testkitv1.TenantConfig{}
	out.Id = src.Id
	out.AppKey = src.AppKey
	out.TenantKey = src.TenantKey
	out.Name = src.Name
	out.Email = src.Email
	out.StrictVersions = src.StrictVersions
	out.AuthMode = telemetryv1.AuthMode(src.AuthMode)
	out.AuthGraceUntil = src.AuthGraceUntil
	out.RatePerMinute = src.RatePerMinute
	out.RatePerDay = src.RatePerDay
	out.RawRetentionDays = src.RawRetentionDays
	out.DailyEventBudget = src.DailyEventBudget
	out.Disabled = src.Disabled
	out.AppSecret = src.AppSecret
	out.CreatedAt = src.CreatedAt
	out.UpdatedAt = src.UpdatedAt
	return out
}

func toDnCreateTenantConfigRequest(src *testkitv1.CreateTenantConfigRequest) *dnv1.CreateTenantConfigRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.CreateTenantConfigRequest{}
	out.Name = src.Name
	out.Email = src.Email
	out.TenantKey = src.TenantKey
	return out
}

func toTestkitCreateTenantConfigRequest(src *dnv1.CreateTenantConfigRequest) *testkitv1.CreateTenantConfigRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.CreateTenantConfigRequest{}
	out.Name = src.Name
	out.Email = src.Email
	out.TenantKey = src.TenantKey
	return out
}

func toDnCreateTenantConfigResponse(src *testkitv1.CreateTenantConfigResponse) *dnv1.CreateTenantConfigResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.CreateTenantConfigResponse{}
	out.Config = toDnTenantConfig(src.Config)
	out.Token = src.Token
	return out
}

func toTestkitCreateTenantConfigResponse(src *dnv1.CreateTenantConfigResponse) *testkitv1.CreateTenantConfigResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.CreateTenantConfigResponse{}
	out.Config = toTestkitTenantConfig(src.Config)
	out.Token = src.Token
	out.AppSecret = src.AppSecret
	return out
}

func toDnCreateSigningKeyRequest(src *testkitv1.CreateSigningKeyRequest) *dnv1.CreateSigningKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.CreateSigningKeyRequest{}
	out.TenantKey = src.TenantKey
	out.KeyId = src.KeyId
	return out
}

func toTestkitCreateSigningKeyRequest(src *dnv1.CreateSigningKeyRequest) *testkitv1.CreateSigningKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.CreateSigningKeyRequest{}
	out.TenantKey = src.TenantKey
	out.KeyId = src.KeyId
	return out
}

func toDnCreateSigningKeyResponse(src *testkitv1.CreateSigningKeyResponse) *dnv1.CreateSigningKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.CreateSigningKeyResponse{}
	out.KeyId = src.KeyId
	out.Secret = src.Secret
	return out
}

func toTestkitCreateSigningKeyResponse(src *dnv1.CreateSigningKeyResponse) *testkitv1.CreateSigningKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.CreateSigningKeyResponse{}
	out.KeyId = src.KeyId
	out.Secret = src.Secret
	return out
}

func toDnDailyStat(src *testkitv1.DailyStat) *dnv1.DailyStat {
	if src == nil {
		return nil
	}
	out := &dnv1.DailyStat{}
	out.Day = src.Day
	out.Devices = src.Devices
	out.Events = src.Events
	return out
}

func toTestkitDailyStat(src *dnv1.DailyStat) *testkitv1.DailyStat {
	if src == nil {
		return nil
	}
	out := &testkitv1.DailyStat{}
	out.Day = src.Day
	out.Devices = src.Devices
	out.Events = src.Events
	return out
}

func toDnEventRule(src *testkitv1.EventRule) *dnv1.EventRule {
	if src == nil {
		return nil
	}
	out := &dnv1.EventRule{}
	out.EventName = src.EventName
	out.AllowProps = src.AllowProps
	if src.MapProp != nil {
		out.MapProp = src.MapProp
	}
	return out
}

func toTestkitEventRule(src *dnv1.EventRule) *testkitv1.EventRule {
	if src == nil {
		return nil
	}
	out := &testkitv1.EventRule{}
	out.EventName = src.EventName
	out.AllowProps = src.AllowProps
	if src.MapProp != nil {
		out.MapProp = src.MapProp
	}
	return out
}

func toDnGetTenantConfigRequest(src *testkitv1.GetTenantConfigRequest) *dnv1.GetTenantConfigRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.GetTenantConfigRequest{}
	out.TenantKey = src.TenantKey
	return out
}

func toTestkitGetTenantConfigRequest(src *dnv1.GetTenantConfigRequest) *testkitv1.GetTenantConfigRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.GetTenantConfigRequest{}
	out.TenantKey = src.TenantKey
	return out
}

func toDnGetTenantConfigResponse(src *testkitv1.GetTenantConfigResponse) *dnv1.GetTenantConfigResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.GetTenantConfigResponse{}
	out.Config = toDnTenantConfig(src.Config)
	for _, item := range src.Tokens {
		out.Tokens = append(out.Tokens, toDnIngestTokenInfo(item))
	}
	for _, item := range src.SigningKeys {
		out.SigningKeys = append(out.SigningKeys, toDnSigningKeyInfo(item))
	}
	for _, item := range src.Rules {
		out.Rules = append(out.Rules, toDnEventRule(item))
	}
	for _, item := range src.Versions {
		out.Versions = append(out.Versions, toDnVersionInfo(item))
	}
	return out
}

func toTestkitGetTenantConfigResponse(src *dnv1.GetTenantConfigResponse) *testkitv1.GetTenantConfigResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.GetTenantConfigResponse{}
	out.Config = toTestkitTenantConfig(src.Config)
	for _, item := range src.Tokens {
		out.Tokens = append(out.Tokens, toTestkitIngestTokenInfo(item))
	}
	for _, item := range src.SigningKeys {
		out.SigningKeys = append(out.SigningKeys, toTestkitTelemetrySigningKeyInfo(item))
	}
	for _, item := range src.Rules {
		out.Rules = append(out.Rules, toTestkitEventRule(item))
	}
	for _, item := range src.Versions {
		out.Versions = append(out.Versions, toTestkitVersionInfo(item))
	}
	return out
}

func toDnGetTenantConfigStatsRequest(src *testkitv1.GetTenantConfigStatsRequest) *dnv1.GetTenantConfigStatsRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.GetTenantConfigStatsRequest{}
	out.TenantKey = src.TenantKey
	out.Days = src.Days
	return out
}

func toTestkitGetTenantConfigStatsRequest(src *dnv1.GetTenantConfigStatsRequest) *testkitv1.GetTenantConfigStatsRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.GetTenantConfigStatsRequest{}
	out.TenantKey = src.TenantKey
	out.Days = src.Days
	return out
}

func toDnGetTenantConfigStatsResponse(src *testkitv1.GetTenantConfigStatsResponse) *dnv1.GetTenantConfigStatsResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.GetTenantConfigStatsResponse{}
	for _, item := range src.Days {
		out.Days = append(out.Days, toDnDailyStat(item))
	}
	out.Drops = make(map[string]int64, len(src.Drops))
	for k, v := range src.Drops {
		out.Drops[k] = v
	}
	out.SigFails = make(map[string]int64, len(src.SigFails))
	for k, v := range src.SigFails {
		out.SigFails[k] = v
	}
	return out
}

func toTestkitGetTenantConfigStatsResponse(src *dnv1.GetTenantConfigStatsResponse) *testkitv1.GetTenantConfigStatsResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.GetTenantConfigStatsResponse{}
	for _, item := range src.Days {
		out.Days = append(out.Days, toTestkitDailyStat(item))
	}
	out.Drops = make(map[string]int64, len(src.Drops))
	for k, v := range src.Drops {
		out.Drops[k] = v
	}
	out.SigFails = make(map[string]int64, len(src.SigFails))
	for k, v := range src.SigFails {
		out.SigFails[k] = v
	}
	return out
}

func toDnIngestRequest(src *testkitv1.IngestRequest) *dnv1.IngestRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.IngestRequest{}
	out.Token = src.Token
	out.Body = src.Body
	out.Signature = src.Signature
	return out
}

func toTestkitIngestRequest(src *dnv1.IngestRequest) *testkitv1.IngestRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.IngestRequest{}
	out.Token = src.Token
	out.Body = src.Body
	out.Signature = src.Signature
	return out
}

func toDnIngestResponse(src *testkitv1.IngestResponse) *dnv1.IngestResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.IngestResponse{}
	out.HttpCode = src.HttpCode
	out.ErrorCode = src.ErrorCode
	out.Duplicate = src.Duplicate
	out.Accepted = src.Accepted
	out.Dropped = src.Dropped
	out.Drops = make(map[string]int32, len(src.Drops))
	for k, v := range src.Drops {
		out.Drops[k] = v
	}
	return out
}

func toTestkitIngestResponse(src *dnv1.IngestResponse) *testkitv1.IngestResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.IngestResponse{}
	out.HttpCode = src.HttpCode
	out.ErrorCode = src.ErrorCode
	out.Duplicate = src.Duplicate
	out.Accepted = src.Accepted
	out.Dropped = src.Dropped
	out.Drops = make(map[string]int32, len(src.Drops))
	for k, v := range src.Drops {
		out.Drops[k] = v
	}
	return out
}

func toDnIngestTokenInfo(src *testkitv1.IngestTokenInfo) *dnv1.IngestTokenInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.IngestTokenInfo{}
	out.Prefix = src.Prefix
	out.Revoked = src.Revoked
	out.CreatedAt = src.CreatedAt
	out.LastUsedAt = src.LastUsedAt
	return out
}

func toTestkitIngestTokenInfo(src *dnv1.IngestTokenInfo) *testkitv1.IngestTokenInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.IngestTokenInfo{}
	out.Prefix = src.Prefix
	out.Revoked = src.Revoked
	out.CreatedAt = src.CreatedAt
	out.LastUsedAt = src.LastUsedAt
	return out
}

func toDnReplaceEventRulesRequest(src *testkitv1.ReplaceEventRulesRequest) *dnv1.ReplaceEventRulesRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ReplaceEventRulesRequest{}
	out.TenantKey = src.TenantKey
	for _, item := range src.Rules {
		out.Rules = append(out.Rules, toDnEventRule(item))
	}
	return out
}

func toTestkitReplaceEventRulesRequest(src *dnv1.ReplaceEventRulesRequest) *testkitv1.ReplaceEventRulesRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ReplaceEventRulesRequest{}
	out.TenantKey = src.TenantKey
	for _, item := range src.Rules {
		out.Rules = append(out.Rules, toTestkitEventRule(item))
	}
	return out
}

func toDnReplaceEventRulesResponse(src *testkitv1.ReplaceEventRulesResponse) *dnv1.ReplaceEventRulesResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ReplaceEventRulesResponse{}
	for _, item := range src.Rules {
		out.Rules = append(out.Rules, toDnEventRule(item))
	}
	return out
}

func toTestkitReplaceEventRulesResponse(src *dnv1.ReplaceEventRulesResponse) *testkitv1.ReplaceEventRulesResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ReplaceEventRulesResponse{}
	for _, item := range src.Rules {
		out.Rules = append(out.Rules, toTestkitEventRule(item))
	}
	return out
}

func toDnRevokeSigningKeyRequest(src *testkitv1.RevokeSigningKeyRequest) *dnv1.RevokeSigningKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeSigningKeyRequest{}
	out.TenantKey = src.TenantKey
	out.KeyId = src.KeyId
	return out
}

func toTestkitRevokeSigningKeyRequest(src *dnv1.RevokeSigningKeyRequest) *testkitv1.RevokeSigningKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeSigningKeyRequest{}
	out.TenantKey = src.TenantKey
	out.KeyId = src.KeyId
	return out
}

func toDnRevokeSigningKeyResponse(src *testkitv1.RevokeSigningKeyResponse) *dnv1.RevokeSigningKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeSigningKeyResponse{}

	return out
}

func toTestkitRevokeSigningKeyResponse(src *dnv1.RevokeSigningKeyResponse) *testkitv1.RevokeSigningKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeSigningKeyResponse{}

	return out
}

func toDnRevokeTokenRequest(src *testkitv1.RevokeTokenRequest) *dnv1.RevokeTokenRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeTokenRequest{}
	out.TenantKey = src.TenantKey
	out.Prefix = src.Prefix
	return out
}

func toTestkitRevokeTokenRequest(src *dnv1.RevokeTokenRequest) *testkitv1.RevokeTokenRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeTokenRequest{}
	out.TenantKey = src.TenantKey
	out.Prefix = src.Prefix
	return out
}

func toDnRevokeTokenResponse(src *testkitv1.RevokeTokenResponse) *dnv1.RevokeTokenResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeTokenResponse{}

	return out
}

func toTestkitRevokeTokenResponse(src *dnv1.RevokeTokenResponse) *testkitv1.RevokeTokenResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeTokenResponse{}

	return out
}

func toDnRotateTokenRequest(src *testkitv1.RotateTokenRequest) *dnv1.RotateTokenRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.RotateTokenRequest{}
	out.TenantKey = src.TenantKey
	return out
}

func toTestkitRotateTokenRequest(src *dnv1.RotateTokenRequest) *testkitv1.RotateTokenRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.RotateTokenRequest{}
	out.TenantKey = src.TenantKey
	return out
}

func toDnRotateTokenResponse(src *testkitv1.RotateTokenResponse) *dnv1.RotateTokenResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.RotateTokenResponse{}
	out.Token = src.Token
	return out
}

func toTestkitRotateTokenResponse(src *dnv1.RotateTokenResponse) *testkitv1.RotateTokenResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.RotateTokenResponse{}
	out.Token = src.Token
	return out
}

func toDnSetVersionBlockedRequest(src *testkitv1.SetVersionBlockedRequest) *dnv1.SetVersionBlockedRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.SetVersionBlockedRequest{}
	out.TenantKey = src.TenantKey
	out.Version = src.Version
	out.Blocked = src.Blocked
	return out
}

func toTestkitSetVersionBlockedRequest(src *dnv1.SetVersionBlockedRequest) *testkitv1.SetVersionBlockedRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.SetVersionBlockedRequest{}
	out.TenantKey = src.TenantKey
	out.Version = src.Version
	out.Blocked = src.Blocked
	return out
}

func toDnSetVersionBlockedResponse(src *testkitv1.SetVersionBlockedResponse) *dnv1.SetVersionBlockedResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.SetVersionBlockedResponse{}

	return out
}

func toTestkitSetVersionBlockedResponse(src *dnv1.SetVersionBlockedResponse) *testkitv1.SetVersionBlockedResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.SetVersionBlockedResponse{}

	return out
}

func toDnSigningKeyInfo(src *testkitv1.TelemetrySigningKeyInfo) *dnv1.SigningKeyInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.SigningKeyInfo{}
	out.KeyId = src.KeyId
	out.Revoked = src.Revoked
	out.CreatedAt = src.CreatedAt
	out.LastUsedAt = src.LastUsedAt
	return out
}

func toTestkitTelemetrySigningKeyInfo(src *dnv1.SigningKeyInfo) *testkitv1.TelemetrySigningKeyInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.TelemetrySigningKeyInfo{}
	out.KeyId = src.KeyId
	out.Revoked = src.Revoked
	out.CreatedAt = src.CreatedAt
	out.LastUsedAt = src.LastUsedAt
	return out
}

func toDnUpdateTenantConfigRequest(src *testkitv1.UpdateTenantConfigRequest) *dnv1.UpdateTenantConfigRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.UpdateTenantConfigRequest{}
	out.TenantKey = src.TenantKey
	if src.Name != nil {
		out.Name = src.Name
	}
	if src.Email != nil {
		out.Email = src.Email
	}
	if src.StrictVersions != nil {
		out.StrictVersions = src.StrictVersions
	}
	if src.AuthMode != nil {
		v := dnv1.AuthMode(*src.AuthMode)
		out.AuthMode = &v
	}
	if src.AuthGraceUntil != nil {
		out.AuthGraceUntil = src.AuthGraceUntil
	}
	out.ClearAuthGrace = src.ClearAuthGrace
	if src.RatePerMinute != nil {
		out.RatePerMinute = src.RatePerMinute
	}
	if src.RatePerDay != nil {
		out.RatePerDay = src.RatePerDay
	}
	if src.RawRetentionDays != nil {
		out.RawRetentionDays = src.RawRetentionDays
	}
	if src.DailyEventBudget != nil {
		out.DailyEventBudget = src.DailyEventBudget
	}
	if src.Disabled != nil {
		out.Disabled = src.Disabled
	}
	return out
}

func toTestkitUpdateTenantConfigRequest(src *dnv1.UpdateTenantConfigRequest) *testkitv1.UpdateTenantConfigRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.UpdateTenantConfigRequest{}
	out.TenantKey = src.TenantKey
	if src.Name != nil {
		out.Name = src.Name
	}
	if src.Email != nil {
		out.Email = src.Email
	}
	if src.StrictVersions != nil {
		out.StrictVersions = src.StrictVersions
	}
	if src.AuthMode != nil {
		v := telemetryv1.AuthMode(*src.AuthMode)
		out.AuthMode = &v
	}
	if src.AuthGraceUntil != nil {
		out.AuthGraceUntil = src.AuthGraceUntil
	}
	out.ClearAuthGrace = src.ClearAuthGrace
	if src.RatePerMinute != nil {
		out.RatePerMinute = src.RatePerMinute
	}
	if src.RatePerDay != nil {
		out.RatePerDay = src.RatePerDay
	}
	if src.RawRetentionDays != nil {
		out.RawRetentionDays = src.RawRetentionDays
	}
	if src.DailyEventBudget != nil {
		out.DailyEventBudget = src.DailyEventBudget
	}
	if src.Disabled != nil {
		out.Disabled = src.Disabled
	}
	return out
}

func toDnUpdateTenantConfigResponse(src *testkitv1.UpdateTenantConfigResponse) *dnv1.UpdateTenantConfigResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.UpdateTenantConfigResponse{}
	out.Config = toDnTenantConfig(src.Config)
	return out
}

func toTestkitUpdateTenantConfigResponse(src *dnv1.UpdateTenantConfigResponse) *testkitv1.UpdateTenantConfigResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.UpdateTenantConfigResponse{}
	out.Config = toTestkitTenantConfig(src.Config)
	return out
}

func toDnValidateBatchResponse(src *testkitv1.ValidateBatchResponse) *dnv1.ValidateBatchResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ValidateBatchResponse{}
	out.HttpCode = src.HttpCode
	out.App = src.App
	out.ErrorCode = src.ErrorCode
	out.SignatureValid = src.SignatureValid
	out.SignatureError = src.SignatureError
	out.EnvelopeError = src.EnvelopeError
	for _, item := range src.Events {
		out.Events = append(out.Events, toDnValidateEventResult(item))
	}
	return out
}

func toTestkitValidateBatchResponse(src *dnv1.ValidateBatchResponse) *testkitv1.ValidateBatchResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ValidateBatchResponse{}
	out.HttpCode = src.HttpCode
	out.App = src.App
	out.ErrorCode = src.ErrorCode
	out.SignatureValid = src.SignatureValid
	out.SignatureError = src.SignatureError
	out.EnvelopeError = src.EnvelopeError
	for _, item := range src.Events {
		out.Events = append(out.Events, toTestkitValidateEventResult(item))
	}
	return out
}

func toDnValidateEventResult(src *testkitv1.ValidateEventResult) *dnv1.ValidateEventResult {
	if src == nil {
		return nil
	}
	out := &dnv1.ValidateEventResult{}
	out.Index = src.Index
	out.EventId = src.EventId
	out.Name = src.Name
	out.Accepted = src.Accepted
	out.DropReason = src.DropReason
	return out
}

func toTestkitValidateEventResult(src *dnv1.ValidateEventResult) *testkitv1.ValidateEventResult {
	if src == nil {
		return nil
	}
	out := &testkitv1.ValidateEventResult{}
	out.Index = src.Index
	out.EventId = src.EventId
	out.Name = src.Name
	out.Accepted = src.Accepted
	out.DropReason = src.DropReason
	return out
}

func toDnVersionInfo(src *testkitv1.VersionInfo) *dnv1.VersionInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.VersionInfo{}
	out.Version = src.Version
	out.Blocked = src.Blocked
	out.SeenCount = src.SeenCount
	out.LastSeenAt = src.LastSeenAt
	return out
}

func toTestkitVersionInfo(src *dnv1.VersionInfo) *testkitv1.VersionInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.VersionInfo{}
	out.Version = src.Version
	out.Blocked = src.Blocked
	out.SeenCount = src.SeenCount
	out.LastSeenAt = src.LastSeenAt
	return out
}
