.PHONY: all build run test lint fmt vet tidy regenerate

# Published binary name. Override to ship under a different name without
# touching the source tree, e.g. `make build BIN_NAME=msgsvc`.
# The Go package path stays cmd/server regardless.
BIN_NAME := testkit-service
CMD_DIR  := cmd/server

# Build-time version info injected via -ldflags into internal/version.
# Override with `make build VERSION=v1.2.3`; defaults read from git.
VERSION   ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT    ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
BRANCH    ?= $(shell git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
BUILDTIME := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
VERSION_PKG := testkit-service/internal/version
LDFLAGS := -X $(VERSION_PKG).Version=$(VERSION) \
           -X $(VERSION_PKG).GitCommit=$(COMMIT) \
           -X $(VERSION_PKG).GitBranch=$(BRANCH) \
           -X $(VERSION_PKG).BuildTime=$(BUILDTIME)

## build: Build the $(BIN_NAME) binary (version info injected via -ldflags)
build:
	go build -ldflags "$(LDFLAGS)" -o bin/$(BIN_NAME) ./$(CMD_DIR)/

## run: Run the server locally (auto-copies config.example.yaml -> config.yaml if missing)
run:
	@test -f config.yaml || cp config.example.yaml config.yaml
	go run ./$(CMD_DIR)/

## test: Run tests with race detector
test:
	go test -race -coverprofile=coverage.out ./...

## lint: Run golangci-lint
lint:
	golangci-lint run ./...

## fmt: Format code
fmt:
	gofmt -w .
	goimports -w .

## vet: Run go vet
vet:
	go vet ./...

## tidy: Run go mod tidy
tidy:
	go mod tidy

## regenerate: Re-run all codegen + tidy (call after proto/model changes or template updates)
regenerate: proto tidy

## all: Format, vet, lint, test
all: fmt vet lint test

# BEGIN golang-service-docker
# Generated by golang-service-docker. Rerendering replaces this entire block.

IMAGE_REPOSITORY ?= testkit-service
IMAGE_TAG ?= latest
TARGET_PLATFORM ?=
DOCKER_PLATFORM_ENV = $(if $(strip $(TARGET_PLATFORM)),DOCKER_DEFAULT_PLATFORM=$(TARGET_PLATFORM))
DOCKER_COMPOSE := $(DOCKER_PLATFORM_ENV) IMAGE_REPOSITORY=$(IMAGE_REPOSITORY) IMAGE_TAG=$(IMAGE_TAG) docker compose

.PHONY: docker-build docker-push docker-up docker-migrate docker-down docker-reset docker-logs docker-health

## docker-build: Build the host platform, or pass TARGET_PLATFORM=linux/amd64
docker-build:
	$(DOCKER_COMPOSE) build

## docker-push: Push $(IMAGE_REPOSITORY):$(IMAGE_TAG)
docker-push: docker-build
	$(DOCKER_COMPOSE) push testkit-service

## docker-up: Build and start the selected stack, then wait for healthchecks
docker-up: docker-build
	$(DOCKER_COMPOSE) up --wait --no-build -d

## docker-migrate: One-shot migration against the compose DB (builds, starts deps, runs migrate, exits)
docker-migrate: docker-build
	$(DOCKER_COMPOSE) run --rm testkit-service migrate

## docker-down: Stop containers while preserving named volumes
docker-down:
	$(DOCKER_COMPOSE) down

## docker-reset: Stop containers and deliberately delete named volumes
docker-reset:
	@echo "Deleting Docker volumes for testkit-service"
	$(DOCKER_COMPOSE) down -v

## docker-logs: Follow logs for all services, or pass svc=<service>
docker-logs:
	$(DOCKER_COMPOSE) logs -f --tail=100 $(svc)

## docker-health: Query grpcx health from inside the app container
docker-health:
	$(DOCKER_COMPOSE) exec -T testkit-service grpc_health_probe -addr=127.0.0.1:19095

# END golang-service-docker

## refresh-swagger: copy testkit's generated swagger from the api repo.
## The web client generation (web/package.json "openapi") consumes
## api/swagger/testkit/v1/testkit.swagger.json.
.PHONY: refresh-swagger
refresh-swagger:
	cp ../api/gen/openapi/testkit/v1/service.swagger.json api/swagger/testkit/v1/testkit.swagger.json
