// P6 license/telemetry forwarders — one-line delegations, mirroring the
// pattern of testkit.go. Generated by /tmp/gen_handler.py.
package handler

import (
	"context"

	licensev1 "github.com/servekit/api/gen/go/license/v1"
	testkitv1 "github.com/servekit/api/gen/go/testkit/v1"

	"google.golang.org/protobuf/types/known/emptypb"
)

func (h *Handler) Activate(ctx context.Context, req *testkitv1.ActivateRequest) (*testkitv1.ActivateResponse, error) {
	return h.svc.License().Activate(ctx, req)
}

func (h *Handler) Deactivate(ctx context.Context, req *testkitv1.DeactivateRequest) (*testkitv1.DeactivateResponse, error) {
	return h.svc.License().Deactivate(ctx, req)
}

func (h *Handler) TrialStart(ctx context.Context, req *testkitv1.TrialStartRequest) (*testkitv1.TrialStartResponse, error) {
	return h.svc.License().TrialStart(ctx, req)
}

func (h *Handler) Health(ctx context.Context, req *testkitv1.HealthRequest) (*testkitv1.HealthResponse, error) {
	return h.svc.License().Health(ctx, req)
}

func (h *Handler) CreateKey(ctx context.Context, req *testkitv1.CreateKeyRequest) (*testkitv1.CreateKeyResponse, error) {
	return h.svc.License().CreateKey(ctx, req)
}

func (h *Handler) ShowKey(ctx context.Context, req *testkitv1.ShowKeyRequest) (*testkitv1.ShowKeyResponse, error) {
	return h.svc.License().ShowKey(ctx, req)
}

func (h *Handler) ListKeys(ctx context.Context, req *testkitv1.ListKeysRequest) (*testkitv1.ListKeysResponse, error) {
	return h.svc.License().ListKeys(ctx, req)
}

func (h *Handler) UpdateKey(ctx context.Context, req *testkitv1.UpdateKeyRequest) (*testkitv1.UpdateKeyResponse, error) {
	return h.svc.License().UpdateKey(ctx, req)
}

func (h *Handler) RevokeKey(ctx context.Context, req *testkitv1.RevokeKeyRequest) (*testkitv1.RevokeKeyResponse, error) {
	return h.svc.License().RevokeKey(ctx, req)
}

func (h *Handler) UnrevokeKey(ctx context.Context, req *testkitv1.UnrevokeKeyRequest) (*testkitv1.UnrevokeKeyResponse, error) {
	return h.svc.License().UnrevokeKey(ctx, req)
}

func (h *Handler) DeleteKey(ctx context.Context, req *testkitv1.DeleteKeyRequest) (*testkitv1.DeleteKeyResponse, error) {
	return h.svc.License().DeleteKey(ctx, req)
}

func (h *Handler) GrantModule(ctx context.Context, req *testkitv1.GrantModuleRequest) (*testkitv1.GrantModuleResponse, error) {
	return h.svc.License().GrantModule(ctx, req)
}

func (h *Handler) RevokeModule(ctx context.Context, req *testkitv1.RevokeModuleRequest) (*testkitv1.RevokeModuleResponse, error) {
	return h.svc.License().RevokeModule(ctx, req)
}

func (h *Handler) ListKeyDevices(ctx context.Context, req *testkitv1.ListKeyDevicesRequest) (*testkitv1.ListKeyDevicesResponse, error) {
	return h.svc.License().ListKeyDevices(ctx, req)
}

func (h *Handler) KickDevice(ctx context.Context, req *testkitv1.KickDeviceRequest) (*testkitv1.KickDeviceResponse, error) {
	return h.svc.License().KickDevice(ctx, req)
}

func (h *Handler) ShowTrial(ctx context.Context, req *testkitv1.ShowTrialRequest) (*testkitv1.ShowTrialResponse, error) {
	return h.svc.License().ShowTrial(ctx, req)
}

func (h *Handler) ResetTrial(ctx context.Context, req *testkitv1.ResetTrialRequest) (*testkitv1.ResetTrialResponse, error) {
	return h.svc.License().ResetTrial(ctx, req)
}

func (h *Handler) ShowPubKey(ctx context.Context, req *testkitv1.ShowPubKeyRequest) (*testkitv1.ShowPubKeyResponse, error) {
	return h.svc.License().ShowPubKey(ctx, req)
}

// --- app-registry forwards (calling applications; license.v1 types) ---

func (h *Handler) LicenseCreateTenantConfig(ctx context.Context, req *licensev1.CreateTenantConfigRequest) (*licensev1.CreateTenantConfigResponse, error) {
	return h.svc.License().LicenseCreateTenantConfig(ctx, req)
}

func (h *Handler) LicenseGetTenantConfig(ctx context.Context, req *licensev1.GetTenantConfigRequest) (*licensev1.GetTenantConfigResponse, error) {
	return h.svc.License().LicenseGetTenantConfig(ctx, req)
}

func (h *Handler) LicenseUpdateTenantConfig(ctx context.Context, req *licensev1.UpdateTenantConfigRequest) (*licensev1.UpdateTenantConfigResponse, error) {
	return h.svc.License().LicenseUpdateTenantConfig(ctx, req)
}

func (h *Handler) LicenseListTenantConfigs(ctx context.Context, req *licensev1.ListTenantConfigsRequest) (*licensev1.ListTenantConfigsResponse, error) {
	return h.svc.License().LicenseListTenantConfigs(ctx, req)
}

func (h *Handler) LicenseDeleteTenantConfig(ctx context.Context, req *licensev1.DeleteTenantConfigRequest) (*emptypb.Empty, error) {
	return h.svc.License().LicenseDeleteTenantConfig(ctx, req)
}
