// P6 license/telemetry forwarders — one-line delegations, mirroring the
// pattern of testkit.go. Generated by /tmp/gen_handler.py.
package handler

import (
	"context"

	licensev1 "github.com/servekit/api/gen/go/license/v1"
	testkitv1 "github.com/servekit/api/gen/go/testkit/v1"

	"google.golang.org/protobuf/types/known/emptypb"
)

func (h *Handler) Activate(ctx context.Context, req *testkitv1.ActivateRequest) (*testkitv1.ActivateResponse, error) {
	return h.svc.License().Activate(ctx, req)
}

func (h *Handler) Deactivate(ctx context.Context, req *testkitv1.DeactivateRequest) (*testkitv1.DeactivateResponse, error) {
	return h.svc.License().Deactivate(ctx, req)
}

func (h *Handler) TrialStart(ctx context.Context, req *testkitv1.TrialStartRequest) (*testkitv1.TrialStartResponse, error) {
	return h.svc.License().TrialStart(ctx, req)
}

func (h *Handler) Health(ctx context.Context, req *testkitv1.HealthRequest) (*testkitv1.HealthResponse, error) {
	return h.svc.License().Health(ctx, req)
}

func (h *Handler) CreateKey(ctx context.Context, req *testkitv1.CreateKeyRequest) (*testkitv1.CreateKeyResponse, error) {
	return h.svc.License().CreateKey(ctx, req)
}

func (h *Handler) ShowKey(ctx context.Context, req *testkitv1.ShowKeyRequest) (*testkitv1.ShowKeyResponse, error) {
	return h.svc.License().ShowKey(ctx, req)
}

func (h *Handler) ListKeys(ctx context.Context, req *testkitv1.ListKeysRequest) (*testkitv1.ListKeysResponse, error) {
	return h.svc.License().ListKeys(ctx, req)
}

func (h *Handler) UpdateKey(ctx context.Context, req *testkitv1.UpdateKeyRequest) (*testkitv1.UpdateKeyResponse, error) {
	return h.svc.License().UpdateKey(ctx, req)
}

func (h *Handler) RevokeKey(ctx context.Context, req *testkitv1.RevokeKeyRequest) (*testkitv1.RevokeKeyResponse, error) {
	return h.svc.License().RevokeKey(ctx, req)
}

func (h *Handler) UnrevokeKey(ctx context.Context, req *testkitv1.UnrevokeKeyRequest) (*testkitv1.UnrevokeKeyResponse, error) {
	return h.svc.License().UnrevokeKey(ctx, req)
}

func (h *Handler) DeleteKey(ctx context.Context, req *testkitv1.DeleteKeyRequest) (*testkitv1.DeleteKeyResponse, error) {
	return h.svc.License().DeleteKey(ctx, req)
}

func (h *Handler) GrantModule(ctx context.Context, req *testkitv1.GrantModuleRequest) (*testkitv1.GrantModuleResponse, error) {
	return h.svc.License().GrantModule(ctx, req)
}

func (h *Handler) RevokeModule(ctx context.Context, req *testkitv1.RevokeModuleRequest) (*testkitv1.RevokeModuleResponse, error) {
	return h.svc.License().RevokeModule(ctx, req)
}

func (h *Handler) ListKeyDevices(ctx context.Context, req *testkitv1.ListKeyDevicesRequest) (*testkitv1.ListKeyDevicesResponse, error) {
	return h.svc.License().ListKeyDevices(ctx, req)
}

func (h *Handler) KickDevice(ctx context.Context, req *testkitv1.KickDeviceRequest) (*testkitv1.KickDeviceResponse, error) {
	return h.svc.License().KickDevice(ctx, req)
}

func (h *Handler) ShowTrial(ctx context.Context, req *testkitv1.ShowTrialRequest) (*testkitv1.ShowTrialResponse, error) {
	return h.svc.License().ShowTrial(ctx, req)
}

func (h *Handler) ResetTrial(ctx context.Context, req *testkitv1.ResetTrialRequest) (*testkitv1.ResetTrialResponse, error) {
	return h.svc.License().ResetTrial(ctx, req)
}

func (h *Handler) ShowPubKey(ctx context.Context, req *testkitv1.ShowPubKeyRequest) (*testkitv1.ShowPubKeyResponse, error) {
	return h.svc.License().ShowPubKey(ctx, req)
}

// --- app-registry forwards (calling applications; license.v1 types) ---

func (h *Handler) LicenseCreateApp(ctx context.Context, req *licensev1.CreateAppRequest) (*licensev1.CreateAppResponse, error) {
	return h.svc.License().LicenseCreateApp(ctx, req)
}

func (h *Handler) LicenseGetApp(ctx context.Context, req *licensev1.GetAppRequest) (*licensev1.GetAppResponse, error) {
	return h.svc.License().LicenseGetApp(ctx, req)
}

func (h *Handler) LicenseUpdateApp(ctx context.Context, req *licensev1.UpdateAppRequest) (*licensev1.UpdateAppResponse, error) {
	return h.svc.License().LicenseUpdateApp(ctx, req)
}

func (h *Handler) LicenseRotateAppSecret(ctx context.Context, req *licensev1.RotateAppSecretRequest) (*licensev1.RotateAppSecretResponse, error) {
	return h.svc.License().LicenseRotateAppSecret(ctx, req)
}

func (h *Handler) LicenseListApps(ctx context.Context, req *licensev1.ListAppsRequest) (*licensev1.ListAppsResponse, error) {
	return h.svc.License().LicenseListApps(ctx, req)
}

func (h *Handler) LicenseDeleteApp(ctx context.Context, req *licensev1.DeleteAppRequest) (*emptypb.Empty, error) {
	return h.svc.License().LicenseDeleteApp(ctx, req)
}
