// P6 license/telemetry forwarders — one-line delegations, mirroring the
// pattern of testkit.go. Generated by /tmp/gen_handler.py.
package handler

import (
	"context"

	telemetryv1 "github.com/servekit/api/gen/go/telemetry/v1"
	testkitv1 "github.com/servekit/api/gen/go/testkit/v1"
)

func (h *Handler) Ingest(ctx context.Context, req *testkitv1.IngestRequest) (*testkitv1.IngestResponse, error) {
	return h.svc.Telemetry().Ingest(ctx, req)
}

func (h *Handler) CreateApp(ctx context.Context, req *testkitv1.CreateAppRequest) (*testkitv1.CreateAppResponse, error) {
	return h.svc.Telemetry().CreateApp(ctx, req)
}

func (h *Handler) GetApp(ctx context.Context, req *testkitv1.GetAppRequest) (*testkitv1.GetAppResponse, error) {
	return h.svc.Telemetry().GetApp(ctx, req)
}

func (h *Handler) UpdateApp(ctx context.Context, req *testkitv1.UpdateAppRequest) (*testkitv1.UpdateAppResponse, error) {
	return h.svc.Telemetry().UpdateApp(ctx, req)
}

func (h *Handler) RotateToken(ctx context.Context, req *testkitv1.RotateTokenRequest) (*testkitv1.RotateTokenResponse, error) {
	return h.svc.Telemetry().RotateToken(ctx, req)
}

func (h *Handler) RevokeToken(ctx context.Context, req *testkitv1.RevokeTokenRequest) (*testkitv1.RevokeTokenResponse, error) {
	return h.svc.Telemetry().RevokeToken(ctx, req)
}

func (h *Handler) CreateSigningKey(ctx context.Context, req *testkitv1.CreateSigningKeyRequest) (*testkitv1.CreateSigningKeyResponse, error) {
	return h.svc.Telemetry().CreateSigningKey(ctx, req)
}

func (h *Handler) RevokeSigningKey(ctx context.Context, req *testkitv1.RevokeSigningKeyRequest) (*testkitv1.RevokeSigningKeyResponse, error) {
	return h.svc.Telemetry().RevokeSigningKey(ctx, req)
}

func (h *Handler) ReplaceEventRules(ctx context.Context, req *testkitv1.ReplaceEventRulesRequest) (*testkitv1.ReplaceEventRulesResponse, error) {
	return h.svc.Telemetry().ReplaceEventRules(ctx, req)
}

func (h *Handler) SetVersionBlocked(ctx context.Context, req *testkitv1.SetVersionBlockedRequest) (*testkitv1.SetVersionBlockedResponse, error) {
	return h.svc.Telemetry().SetVersionBlocked(ctx, req)
}

func (h *Handler) GetAppStats(ctx context.Context, req *testkitv1.GetAppStatsRequest) (*testkitv1.GetAppStatsResponse, error) {
	return h.svc.Telemetry().GetAppStats(ctx, req)
}

func (h *Handler) ListApps(ctx context.Context, req *telemetryv1.ListAppsRequest) (*telemetryv1.ListAppsResponse, error) {
	return h.svc.Telemetry().ListApps(ctx, req)
}

func (h *Handler) RotateAppSecret(ctx context.Context, req *telemetryv1.RotateAppSecretRequest) (*telemetryv1.RotateAppSecretResponse, error) {
	return h.svc.Telemetry().RotateAppSecret(ctx, req)
}
