// P6 license/telemetry forwarders — one-line delegations, mirroring the
// pattern of testkit.go. Generated by /tmp/gen_handler.py.
package handler

import (
	"context"

	telemetryv1 "github.com/servekit/api/gen/go/telemetry/v1"
	testkitv1 "github.com/servekit/api/gen/go/testkit/v1"
)

func (h *Handler) Ingest(ctx context.Context, req *testkitv1.IngestRequest) (*testkitv1.IngestResponse, error) {
	return h.svc.Telemetry().Ingest(ctx, req)
}

func (h *Handler) CreateTenantConfig(ctx context.Context, req *testkitv1.CreateTenantConfigRequest) (*testkitv1.CreateTenantConfigResponse, error) {
	return h.svc.Telemetry().CreateTenantConfig(ctx, req)
}

func (h *Handler) GetTenantConfig(ctx context.Context, req *testkitv1.GetTenantConfigRequest) (*testkitv1.GetTenantConfigResponse, error) {
	return h.svc.Telemetry().GetTenantConfig(ctx, req)
}

func (h *Handler) UpdateTenantConfig(ctx context.Context, req *testkitv1.UpdateTenantConfigRequest) (*testkitv1.UpdateTenantConfigResponse, error) {
	return h.svc.Telemetry().UpdateTenantConfig(ctx, req)
}

func (h *Handler) RotateToken(ctx context.Context, req *testkitv1.RotateTokenRequest) (*testkitv1.RotateTokenResponse, error) {
	return h.svc.Telemetry().RotateToken(ctx, req)
}

func (h *Handler) RevokeToken(ctx context.Context, req *testkitv1.RevokeTokenRequest) (*testkitv1.RevokeTokenResponse, error) {
	return h.svc.Telemetry().RevokeToken(ctx, req)
}

func (h *Handler) CreateSigningKey(ctx context.Context, req *testkitv1.CreateSigningKeyRequest) (*testkitv1.CreateSigningKeyResponse, error) {
	return h.svc.Telemetry().CreateSigningKey(ctx, req)
}

func (h *Handler) RevokeSigningKey(ctx context.Context, req *testkitv1.RevokeSigningKeyRequest) (*testkitv1.RevokeSigningKeyResponse, error) {
	return h.svc.Telemetry().RevokeSigningKey(ctx, req)
}

func (h *Handler) ReplaceEventRules(ctx context.Context, req *testkitv1.ReplaceEventRulesRequest) (*testkitv1.ReplaceEventRulesResponse, error) {
	return h.svc.Telemetry().ReplaceEventRules(ctx, req)
}

func (h *Handler) SetVersionBlocked(ctx context.Context, req *testkitv1.SetVersionBlockedRequest) (*testkitv1.SetVersionBlockedResponse, error) {
	return h.svc.Telemetry().SetVersionBlocked(ctx, req)
}

func (h *Handler) GetTenantConfigStats(ctx context.Context, req *testkitv1.GetTenantConfigStatsRequest) (*testkitv1.GetTenantConfigStatsResponse, error) {
	return h.svc.Telemetry().GetTenantConfigStats(ctx, req)
}

func (h *Handler) ListTenantConfigs(ctx context.Context, req *telemetryv1.ListTenantConfigsRequest) (*telemetryv1.ListTenantConfigsResponse, error) {
	return h.svc.Telemetry().ListTenantConfigs(ctx, req)
}

func (h *Handler) RotateTenantConfigSecret(ctx context.Context, req *telemetryv1.RotateTenantConfigSecretRequest) (*telemetryv1.RotateTenantConfigSecretResponse, error) {
	return h.svc.Telemetry().RotateTenantConfigSecret(ctx, req)
}
