// Package license forwards testkit's license-service domain (P6) to the
// embedded license-service module. Messages mirror the downstream proto 1:1,
// so every converter below is a field-identical copy (enums int-cast,
// sub-messages recursive). Regenerated by /tmp/gen_forward.py.
package license

import (
	"context"

	dnv1 "github.com/servekit/license-service/gen/license/v1"
	licenseservice "github.com/servekit/license-service/pkg"
	testkitv1 "github.com/servekit/testkit-service/gen/testkit/v1"
	"google.golang.org/grpc/metadata"
)

// Service holds the license-service client (module or grpc mode — the
// pkg.Service interface covers both).
type Service struct {
	client licenseservice.Service
	// adminToken is forwarded as `Authorization: Bearer <token>`
	// metadata on admin-surface RPCs (telemetry-service guards them;
	// license-service has no guard today — empty token is a no-op).
	adminToken string
}

// New builds the license domain service.
func New(client licenseservice.Service, adminToken string) *Service {
	return &Service{client: client, adminToken: adminToken}
}

// adminCtx appends the admin Bearer token to the outgoing metadata.
func (s *Service) adminCtx(ctx context.Context) context.Context {
	if s.adminToken == "" {
		return ctx
	}
	return metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer "+s.adminToken)
}
func (s *Service) Activate(ctx context.Context, req *testkitv1.ActivateRequest) (*testkitv1.ActivateResponse, error) {
	resp, err := s.client.Activate(ctx, toDnActivateRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitActivateResponse(resp), nil
}

func (s *Service) Deactivate(ctx context.Context, req *testkitv1.DeactivateRequest) (*testkitv1.DeactivateResponse, error) {
	resp, err := s.client.Deactivate(ctx, toDnDeactivateRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitDeactivateResponse(resp), nil
}

func (s *Service) TrialStart(ctx context.Context, req *testkitv1.TrialStartRequest) (*testkitv1.TrialStartResponse, error) {
	resp, err := s.client.TrialStart(ctx, toDnTrialStartRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitTrialStartResponse(resp), nil
}

func (s *Service) Health(ctx context.Context, req *testkitv1.HealthRequest) (*testkitv1.HealthResponse, error) {
	resp, err := s.client.Health(ctx, toDnHealthRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitHealthResponse(resp), nil
}

func (s *Service) CreateKey(ctx context.Context, req *testkitv1.CreateKeyRequest) (*testkitv1.CreateKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.CreateKey(ctx, toDnCreateKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitCreateKeyResponse(resp), nil
}

func (s *Service) ShowKey(ctx context.Context, req *testkitv1.ShowKeyRequest) (*testkitv1.ShowKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ShowKey(ctx, toDnShowKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitShowKeyResponse(resp), nil
}

func (s *Service) ListKeys(ctx context.Context, req *testkitv1.ListKeysRequest) (*testkitv1.ListKeysResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ListKeys(ctx, toDnListKeysRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitListKeysResponse(resp), nil
}

func (s *Service) UpdateKey(ctx context.Context, req *testkitv1.UpdateKeyRequest) (*testkitv1.UpdateKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.UpdateKey(ctx, toDnUpdateKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitUpdateKeyResponse(resp), nil
}

func (s *Service) RevokeKey(ctx context.Context, req *testkitv1.RevokeKeyRequest) (*testkitv1.RevokeKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.RevokeKey(ctx, toDnRevokeKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitRevokeKeyResponse(resp), nil
}

func (s *Service) UnrevokeKey(ctx context.Context, req *testkitv1.UnrevokeKeyRequest) (*testkitv1.UnrevokeKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.UnrevokeKey(ctx, toDnUnrevokeKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitUnrevokeKeyResponse(resp), nil
}

func (s *Service) DeleteKey(ctx context.Context, req *testkitv1.DeleteKeyRequest) (*testkitv1.DeleteKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.DeleteKey(ctx, toDnDeleteKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitDeleteKeyResponse(resp), nil
}

func (s *Service) GrantModule(ctx context.Context, req *testkitv1.GrantModuleRequest) (*testkitv1.GrantModuleResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.GrantModule(ctx, toDnGrantModuleRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitGrantModuleResponse(resp), nil
}

func (s *Service) RevokeModule(ctx context.Context, req *testkitv1.RevokeModuleRequest) (*testkitv1.RevokeModuleResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.RevokeModule(ctx, toDnRevokeModuleRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitRevokeModuleResponse(resp), nil
}

func (s *Service) ListKeyDevices(ctx context.Context, req *testkitv1.ListKeyDevicesRequest) (*testkitv1.ListKeyDevicesResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ListKeyDevices(ctx, toDnListKeyDevicesRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitListKeyDevicesResponse(resp), nil
}

func (s *Service) KickDevice(ctx context.Context, req *testkitv1.KickDeviceRequest) (*testkitv1.KickDeviceResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.KickDevice(ctx, toDnKickDeviceRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitKickDeviceResponse(resp), nil
}

func (s *Service) ShowTrial(ctx context.Context, req *testkitv1.ShowTrialRequest) (*testkitv1.ShowTrialResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ShowTrial(ctx, toDnShowTrialRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitShowTrialResponse(resp), nil
}

func (s *Service) ResetTrial(ctx context.Context, req *testkitv1.ResetTrialRequest) (*testkitv1.ResetTrialResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ResetTrial(ctx, toDnResetTrialRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitResetTrialResponse(resp), nil
}

func (s *Service) ShowPubKey(ctx context.Context, req *testkitv1.ShowPubKeyRequest) (*testkitv1.ShowPubKeyResponse, error) {
	ctx = s.adminCtx(ctx)
	resp, err := s.client.ShowPubKey(ctx, toDnShowPubKeyRequest(req))
	if err != nil {
		return nil, err
	}
	return toTestkitShowPubKeyResponse(resp), nil
}

func toDnActivateRequest(src *testkitv1.ActivateRequest) *dnv1.ActivateRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ActivateRequest{}
	out.Key = src.Key
	out.LicenseKey = src.LicenseKey
	out.FingerprintId = src.FingerprintId
	out.DeviceToken = src.DeviceToken
	if src.EvictDeviceToken != nil {
		out.EvictDeviceToken = src.EvictDeviceToken
	}
	return out
}

func toTestkitActivateRequest(src *dnv1.ActivateRequest) *testkitv1.ActivateRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ActivateRequest{}
	out.Key = src.Key
	out.LicenseKey = src.LicenseKey
	out.FingerprintId = src.FingerprintId
	out.DeviceToken = src.DeviceToken
	if src.EvictDeviceToken != nil {
		out.EvictDeviceToken = src.EvictDeviceToken
	}
	return out
}

func toDnActivateResponse(src *testkitv1.ActivateResponse) *dnv1.ActivateResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ActivateResponse{}
	out.Payload = src.Payload
	out.Signature = src.Signature
	out.Slots = toDnSlotSummary(src.Slots)
	return out
}

func toTestkitActivateResponse(src *dnv1.ActivateResponse) *testkitv1.ActivateResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ActivateResponse{}
	out.Payload = src.Payload
	out.Signature = src.Signature
	out.Slots = toTestkitSlotSummary(src.Slots)
	return out
}

func toDnCreateKeyRequest(src *testkitv1.CreateKeyRequest) *dnv1.CreateKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.CreateKeyRequest{}
	out.Label = src.Label
	out.Slots = src.Slots
	for _, item := range src.Grants {
		out.Grants = append(out.Grants, toDnEntitlementInput(item))
	}
	return out
}

func toTestkitCreateKeyRequest(src *dnv1.CreateKeyRequest) *testkitv1.CreateKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.CreateKeyRequest{}
	out.Label = src.Label
	out.Slots = src.Slots
	for _, item := range src.Grants {
		out.Grants = append(out.Grants, toTestkitEntitlementInput(item))
	}
	return out
}

func toDnCreateKeyResponse(src *testkitv1.CreateKeyResponse) *dnv1.CreateKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.CreateKeyResponse{}
	out.Key = toDnKeyInfo(src.Key)
	out.PlaintextKey = src.PlaintextKey
	return out
}

func toTestkitCreateKeyResponse(src *dnv1.CreateKeyResponse) *testkitv1.CreateKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.CreateKeyResponse{}
	out.Key = toTestkitKeyInfo(src.Key)
	out.PlaintextKey = src.PlaintextKey
	return out
}

func toDnDeactivateRequest(src *testkitv1.DeactivateRequest) *dnv1.DeactivateRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.DeactivateRequest{}
	out.Key = src.Key
	out.LicenseKey = src.LicenseKey
	out.DeviceToken = src.DeviceToken
	return out
}

func toTestkitDeactivateRequest(src *dnv1.DeactivateRequest) *testkitv1.DeactivateRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.DeactivateRequest{}
	out.Key = src.Key
	out.LicenseKey = src.LicenseKey
	out.DeviceToken = src.DeviceToken
	return out
}

func toDnDeactivateResponse(src *testkitv1.DeactivateResponse) *dnv1.DeactivateResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.DeactivateResponse{}
	out.Released = src.Released
	return out
}

func toTestkitDeactivateResponse(src *dnv1.DeactivateResponse) *testkitv1.DeactivateResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.DeactivateResponse{}
	out.Released = src.Released
	return out
}

func toDnDeleteKeyRequest(src *testkitv1.DeleteKeyRequest) *dnv1.DeleteKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.DeleteKeyRequest{}
	out.KeyId = src.KeyId
	if src.Confirm != nil {
		out.Confirm = src.Confirm
	}
	return out
}

func toTestkitDeleteKeyRequest(src *dnv1.DeleteKeyRequest) *testkitv1.DeleteKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.DeleteKeyRequest{}
	out.KeyId = src.KeyId
	if src.Confirm != nil {
		out.Confirm = src.Confirm
	}
	return out
}

func toDnDeleteKeyResponse(src *testkitv1.DeleteKeyResponse) *dnv1.DeleteKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.DeleteKeyResponse{}

	return out
}

func toTestkitDeleteKeyResponse(src *dnv1.DeleteKeyResponse) *testkitv1.DeleteKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.DeleteKeyResponse{}

	return out
}

func toDnDeviceSlotInfo(src *testkitv1.DeviceSlotInfo) *dnv1.DeviceSlotInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.DeviceSlotInfo{}
	out.DeviceToken = src.DeviceToken
	out.FingerprintId = src.FingerprintId
	out.FirstSeenAt = src.FirstSeenAt
	out.LastSeenAt = src.LastSeenAt
	if src.Name != nil {
		out.Name = src.Name
	}
	return out
}

func toTestkitDeviceSlotInfo(src *dnv1.DeviceSlotInfo) *testkitv1.DeviceSlotInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.DeviceSlotInfo{}
	out.DeviceToken = src.DeviceToken
	out.FingerprintId = src.FingerprintId
	out.FirstSeenAt = src.FirstSeenAt
	out.LastSeenAt = src.LastSeenAt
	if src.Name != nil {
		out.Name = src.Name
	}
	return out
}

func toDnEntitlementInfo(src *testkitv1.EntitlementInfo) *dnv1.EntitlementInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.EntitlementInfo{}
	out.Module = dnv1.Module(src.Module)
	out.Kind = dnv1.EntitlementKind(src.Kind)
	out.ExpiresAt = src.ExpiresAt
	out.GrantedAt = src.GrantedAt
	return out
}

func toTestkitEntitlementInfo(src *dnv1.EntitlementInfo) *testkitv1.EntitlementInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.EntitlementInfo{}
	out.Module = testkitv1.Module(src.Module)
	out.Kind = testkitv1.EntitlementKind(src.Kind)
	out.ExpiresAt = src.ExpiresAt
	out.GrantedAt = src.GrantedAt
	return out
}

func toDnEntitlementInput(src *testkitv1.EntitlementInput) *dnv1.EntitlementInput {
	if src == nil {
		return nil
	}
	out := &dnv1.EntitlementInput{}
	out.Module = dnv1.Module(src.Module)
	out.Kind = dnv1.EntitlementKind(src.Kind)
	out.DurationDays = src.DurationDays
	out.ExpiresAt = src.ExpiresAt
	return out
}

func toTestkitEntitlementInput(src *dnv1.EntitlementInput) *testkitv1.EntitlementInput {
	if src == nil {
		return nil
	}
	out := &testkitv1.EntitlementInput{}
	out.Module = testkitv1.Module(src.Module)
	out.Kind = testkitv1.EntitlementKind(src.Kind)
	out.DurationDays = src.DurationDays
	out.ExpiresAt = src.ExpiresAt
	return out
}

func toDnGrantModuleRequest(src *testkitv1.GrantModuleRequest) *dnv1.GrantModuleRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.GrantModuleRequest{}
	out.KeyId = src.KeyId
	out.Module = dnv1.Module(src.Module)
	out.Kind = dnv1.EntitlementKind(src.Kind)
	out.DurationDays = src.DurationDays
	out.ExpiresAt = src.ExpiresAt
	return out
}

func toTestkitGrantModuleRequest(src *dnv1.GrantModuleRequest) *testkitv1.GrantModuleRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.GrantModuleRequest{}
	out.KeyId = src.KeyId
	out.Module = testkitv1.Module(src.Module)
	out.Kind = testkitv1.EntitlementKind(src.Kind)
	out.DurationDays = src.DurationDays
	out.ExpiresAt = src.ExpiresAt
	return out
}

func toDnGrantModuleResponse(src *testkitv1.GrantModuleResponse) *dnv1.GrantModuleResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.GrantModuleResponse{}
	out.Entitlement = toDnEntitlementInfo(src.Entitlement)
	return out
}

func toTestkitGrantModuleResponse(src *dnv1.GrantModuleResponse) *testkitv1.GrantModuleResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.GrantModuleResponse{}
	out.Entitlement = toTestkitEntitlementInfo(src.Entitlement)
	return out
}

func toDnHealthChecks(src *testkitv1.HealthChecks) *dnv1.HealthChecks {
	if src == nil {
		return nil
	}
	out := &dnv1.HealthChecks{}
	out.Db = src.Db
	out.Signing = src.Signing
	return out
}

func toTestkitHealthChecks(src *dnv1.HealthChecks) *testkitv1.HealthChecks {
	if src == nil {
		return nil
	}
	out := &testkitv1.HealthChecks{}
	out.Db = src.Db
	out.Signing = src.Signing
	return out
}

func toDnHealthRequest(src *testkitv1.HealthRequest) *dnv1.HealthRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.HealthRequest{}

	return out
}

func toTestkitHealthRequest(src *dnv1.HealthRequest) *testkitv1.HealthRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.HealthRequest{}

	return out
}

func toDnHealthResponse(src *testkitv1.HealthResponse) *dnv1.HealthResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.HealthResponse{}
	out.Status = src.Status
	out.Checks = toDnHealthChecks(src.Checks)
	return out
}

func toTestkitHealthResponse(src *dnv1.HealthResponse) *testkitv1.HealthResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.HealthResponse{}
	out.Status = src.Status
	out.Checks = toTestkitHealthChecks(src.Checks)
	return out
}

func toDnKeyInfo(src *testkitv1.KeyInfo) *dnv1.KeyInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.KeyInfo{}
	out.LicenseId = src.LicenseId
	out.KeyPrefix = src.KeyPrefix
	out.Label = src.Label
	out.MaxSlots = src.MaxSlots
	out.UsedSlots = src.UsedSlots
	out.Status = dnv1.KeyStatus(src.Status)
	out.CreatedAt = src.CreatedAt
	out.RevokedAt = src.RevokedAt
	for _, item := range src.Entitlements {
		out.Entitlements = append(out.Entitlements, toDnEntitlementInfo(item))
	}
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toDnDeviceSlotInfo(item))
	}
	return out
}

func toTestkitKeyInfo(src *dnv1.KeyInfo) *testkitv1.KeyInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.KeyInfo{}
	out.LicenseId = src.LicenseId
	out.KeyPrefix = src.KeyPrefix
	out.Label = src.Label
	out.MaxSlots = src.MaxSlots
	out.UsedSlots = src.UsedSlots
	out.Status = testkitv1.KeyStatus(src.Status)
	out.CreatedAt = src.CreatedAt
	out.RevokedAt = src.RevokedAt
	for _, item := range src.Entitlements {
		out.Entitlements = append(out.Entitlements, toTestkitEntitlementInfo(item))
	}
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toTestkitDeviceSlotInfo(item))
	}
	return out
}

func toDnKickDeviceRequest(src *testkitv1.KickDeviceRequest) *dnv1.KickDeviceRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.KickDeviceRequest{}
	out.KeyId = src.KeyId
	out.DeviceToken = src.DeviceToken
	if src.Reason != nil {
		out.Reason = src.Reason
	}
	return out
}

func toTestkitKickDeviceRequest(src *dnv1.KickDeviceRequest) *testkitv1.KickDeviceRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.KickDeviceRequest{}
	out.KeyId = src.KeyId
	out.DeviceToken = src.DeviceToken
	if src.Reason != nil {
		out.Reason = src.Reason
	}
	return out
}

func toDnKickDeviceResponse(src *testkitv1.KickDeviceResponse) *dnv1.KickDeviceResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.KickDeviceResponse{}
	out.Kicked = src.Kicked
	return out
}

func toTestkitKickDeviceResponse(src *dnv1.KickDeviceResponse) *testkitv1.KickDeviceResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.KickDeviceResponse{}
	out.Kicked = src.Kicked
	return out
}

func toDnListKeyDevicesRequest(src *testkitv1.ListKeyDevicesRequest) *dnv1.ListKeyDevicesRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ListKeyDevicesRequest{}
	out.KeyId = src.KeyId
	return out
}

func toTestkitListKeyDevicesRequest(src *dnv1.ListKeyDevicesRequest) *testkitv1.ListKeyDevicesRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ListKeyDevicesRequest{}
	out.KeyId = src.KeyId
	return out
}

func toDnListKeyDevicesResponse(src *testkitv1.ListKeyDevicesResponse) *dnv1.ListKeyDevicesResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ListKeyDevicesResponse{}
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toDnDeviceSlotInfo(item))
	}
	return out
}

func toTestkitListKeyDevicesResponse(src *dnv1.ListKeyDevicesResponse) *testkitv1.ListKeyDevicesResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ListKeyDevicesResponse{}
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toTestkitDeviceSlotInfo(item))
	}
	return out
}

func toDnListKeysRequest(src *testkitv1.ListKeysRequest) *dnv1.ListKeysRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ListKeysRequest{}
	out.Status = dnv1.KeyStatus(src.Status)
	out.Limit = src.Limit
	return out
}

func toTestkitListKeysRequest(src *dnv1.ListKeysRequest) *testkitv1.ListKeysRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ListKeysRequest{}
	out.Status = testkitv1.KeyStatus(src.Status)
	out.Limit = src.Limit
	return out
}

func toDnListKeysResponse(src *testkitv1.ListKeysResponse) *dnv1.ListKeysResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ListKeysResponse{}
	for _, item := range src.Keys {
		out.Keys = append(out.Keys, toDnKeyInfo(item))
	}
	return out
}

func toTestkitListKeysResponse(src *dnv1.ListKeysResponse) *testkitv1.ListKeysResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ListKeysResponse{}
	for _, item := range src.Keys {
		out.Keys = append(out.Keys, toTestkitKeyInfo(item))
	}
	return out
}

func toDnResetTrialRequest(src *testkitv1.ResetTrialRequest) *dnv1.ResetTrialRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ResetTrialRequest{}
	out.FingerprintId = src.FingerprintId
	out.Module = dnv1.Module(src.Module)
	out.Reason = src.Reason
	return out
}

func toTestkitResetTrialRequest(src *dnv1.ResetTrialRequest) *testkitv1.ResetTrialRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ResetTrialRequest{}
	out.FingerprintId = src.FingerprintId
	out.Module = testkitv1.Module(src.Module)
	out.Reason = src.Reason
	return out
}

func toDnResetTrialResponse(src *testkitv1.ResetTrialResponse) *dnv1.ResetTrialResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ResetTrialResponse{}
	out.Reset_ = src.Reset_
	return out
}

func toTestkitResetTrialResponse(src *dnv1.ResetTrialResponse) *testkitv1.ResetTrialResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ResetTrialResponse{}
	out.Reset_ = src.Reset_
	return out
}

func toDnRetryAfterInfo(src *testkitv1.RetryAfterInfo) *dnv1.RetryAfterInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.RetryAfterInfo{}
	out.Seconds = src.Seconds
	return out
}

func toTestkitRetryAfterInfo(src *dnv1.RetryAfterInfo) *testkitv1.RetryAfterInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.RetryAfterInfo{}
	out.Seconds = src.Seconds
	return out
}

func toDnRevokeKeyRequest(src *testkitv1.RevokeKeyRequest) *dnv1.RevokeKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeKeyRequest{}
	out.KeyId = src.KeyId
	if src.Reason != nil {
		out.Reason = src.Reason
	}
	return out
}

func toTestkitRevokeKeyRequest(src *dnv1.RevokeKeyRequest) *testkitv1.RevokeKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeKeyRequest{}
	out.KeyId = src.KeyId
	if src.Reason != nil {
		out.Reason = src.Reason
	}
	return out
}

func toDnRevokeKeyResponse(src *testkitv1.RevokeKeyResponse) *dnv1.RevokeKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeKeyResponse{}
	out.Key = toDnKeyInfo(src.Key)
	return out
}

func toTestkitRevokeKeyResponse(src *dnv1.RevokeKeyResponse) *testkitv1.RevokeKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeKeyResponse{}
	out.Key = toTestkitKeyInfo(src.Key)
	return out
}

func toDnRevokeModuleRequest(src *testkitv1.RevokeModuleRequest) *dnv1.RevokeModuleRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeModuleRequest{}
	out.KeyId = src.KeyId
	out.Module = dnv1.Module(src.Module)
	if src.Reason != nil {
		out.Reason = src.Reason
	}
	return out
}

func toTestkitRevokeModuleRequest(src *dnv1.RevokeModuleRequest) *testkitv1.RevokeModuleRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeModuleRequest{}
	out.KeyId = src.KeyId
	out.Module = testkitv1.Module(src.Module)
	if src.Reason != nil {
		out.Reason = src.Reason
	}
	return out
}

func toDnRevokeModuleResponse(src *testkitv1.RevokeModuleResponse) *dnv1.RevokeModuleResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.RevokeModuleResponse{}

	return out
}

func toTestkitRevokeModuleResponse(src *dnv1.RevokeModuleResponse) *testkitv1.RevokeModuleResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.RevokeModuleResponse{}

	return out
}

func toDnShowKeyRequest(src *testkitv1.ShowKeyRequest) *dnv1.ShowKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ShowKeyRequest{}
	out.KeyId = src.KeyId
	return out
}

func toTestkitShowKeyRequest(src *dnv1.ShowKeyRequest) *testkitv1.ShowKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ShowKeyRequest{}
	out.KeyId = src.KeyId
	return out
}

func toDnShowKeyResponse(src *testkitv1.ShowKeyResponse) *dnv1.ShowKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ShowKeyResponse{}
	out.Key = toDnKeyInfo(src.Key)
	return out
}

func toTestkitShowKeyResponse(src *dnv1.ShowKeyResponse) *testkitv1.ShowKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ShowKeyResponse{}
	out.Key = toTestkitKeyInfo(src.Key)
	return out
}

func toDnShowPubKeyRequest(src *testkitv1.ShowPubKeyRequest) *dnv1.ShowPubKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ShowPubKeyRequest{}

	return out
}

func toTestkitShowPubKeyRequest(src *dnv1.ShowPubKeyRequest) *testkitv1.ShowPubKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ShowPubKeyRequest{}

	return out
}

func toDnShowPubKeyResponse(src *testkitv1.ShowPubKeyResponse) *dnv1.ShowPubKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ShowPubKeyResponse{}
	out.ActiveKeyId = src.ActiveKeyId
	for _, item := range src.Keys {
		out.Keys = append(out.Keys, toDnSigningKeyInfo(item))
	}
	return out
}

func toTestkitShowPubKeyResponse(src *dnv1.ShowPubKeyResponse) *testkitv1.ShowPubKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ShowPubKeyResponse{}
	out.ActiveKeyId = src.ActiveKeyId
	for _, item := range src.Keys {
		out.Keys = append(out.Keys, toTestkitSigningKeyInfo(item))
	}
	return out
}

func toDnShowTrialRequest(src *testkitv1.ShowTrialRequest) *dnv1.ShowTrialRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.ShowTrialRequest{}
	out.FingerprintId = src.FingerprintId
	out.Module = dnv1.Module(src.Module)
	return out
}

func toTestkitShowTrialRequest(src *dnv1.ShowTrialRequest) *testkitv1.ShowTrialRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.ShowTrialRequest{}
	out.FingerprintId = src.FingerprintId
	out.Module = testkitv1.Module(src.Module)
	return out
}

func toDnShowTrialResponse(src *testkitv1.ShowTrialResponse) *dnv1.ShowTrialResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.ShowTrialResponse{}
	for _, item := range src.Trials {
		out.Trials = append(out.Trials, toDnTrialInfo(item))
	}
	return out
}

func toTestkitShowTrialResponse(src *dnv1.ShowTrialResponse) *testkitv1.ShowTrialResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.ShowTrialResponse{}
	for _, item := range src.Trials {
		out.Trials = append(out.Trials, toTestkitTrialInfo(item))
	}
	return out
}

func toDnSigningKeyInfo(src *testkitv1.SigningKeyInfo) *dnv1.SigningKeyInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.SigningKeyInfo{}
	out.KeyId = src.KeyId
	out.PublicKeyB64 = src.PublicKeyB64
	return out
}

func toTestkitSigningKeyInfo(src *dnv1.SigningKeyInfo) *testkitv1.SigningKeyInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.SigningKeyInfo{}
	out.KeyId = src.KeyId
	out.PublicKeyB64 = src.PublicKeyB64
	return out
}

func toDnSlotLimitInfo(src *testkitv1.SlotLimitInfo) *dnv1.SlotLimitInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.SlotLimitInfo{}
	out.MaxSlots = src.MaxSlots
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toDnDeviceSlotInfo(item))
	}
	return out
}

func toTestkitSlotLimitInfo(src *dnv1.SlotLimitInfo) *testkitv1.SlotLimitInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.SlotLimitInfo{}
	out.MaxSlots = src.MaxSlots
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toTestkitDeviceSlotInfo(item))
	}
	return out
}

func toDnSlotSummary(src *testkitv1.SlotSummary) *dnv1.SlotSummary {
	if src == nil {
		return nil
	}
	out := &dnv1.SlotSummary{}
	out.Used = src.Used
	out.Max = src.Max
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toDnDeviceSlotInfo(item))
	}
	return out
}

func toTestkitSlotSummary(src *dnv1.SlotSummary) *testkitv1.SlotSummary {
	if src == nil {
		return nil
	}
	out := &testkitv1.SlotSummary{}
	out.Used = src.Used
	out.Max = src.Max
	for _, item := range src.Devices {
		out.Devices = append(out.Devices, toTestkitDeviceSlotInfo(item))
	}
	return out
}

func toDnTrialInfo(src *testkitv1.TrialInfo) *dnv1.TrialInfo {
	if src == nil {
		return nil
	}
	out := &dnv1.TrialInfo{}
	out.FingerprintId = src.FingerprintId
	out.Module = dnv1.Module(src.Module)
	out.StartedAt = src.StartedAt
	out.ExpiresAt = src.ExpiresAt
	out.FirstDeviceToken = src.FirstDeviceToken
	return out
}

func toTestkitTrialInfo(src *dnv1.TrialInfo) *testkitv1.TrialInfo {
	if src == nil {
		return nil
	}
	out := &testkitv1.TrialInfo{}
	out.FingerprintId = src.FingerprintId
	out.Module = testkitv1.Module(src.Module)
	out.StartedAt = src.StartedAt
	out.ExpiresAt = src.ExpiresAt
	out.FirstDeviceToken = src.FirstDeviceToken
	return out
}

func toDnTrialStartRequest(src *testkitv1.TrialStartRequest) *dnv1.TrialStartRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.TrialStartRequest{}
	out.Module = src.Module
	out.FingerprintId = src.FingerprintId
	out.DeviceToken = src.DeviceToken
	out.LicenseKey = src.LicenseKey
	return out
}

func toTestkitTrialStartRequest(src *dnv1.TrialStartRequest) *testkitv1.TrialStartRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.TrialStartRequest{}
	out.Module = src.Module
	out.FingerprintId = src.FingerprintId
	out.DeviceToken = src.DeviceToken
	out.LicenseKey = src.LicenseKey
	return out
}

func toDnTrialStartResponse(src *testkitv1.TrialStartResponse) *dnv1.TrialStartResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.TrialStartResponse{}
	out.Payload = src.Payload
	out.Signature = src.Signature
	out.AlreadyStarted = src.AlreadyStarted
	return out
}

func toTestkitTrialStartResponse(src *dnv1.TrialStartResponse) *testkitv1.TrialStartResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.TrialStartResponse{}
	out.Payload = src.Payload
	out.Signature = src.Signature
	out.AlreadyStarted = src.AlreadyStarted
	return out
}

func toDnUnrevokeKeyRequest(src *testkitv1.UnrevokeKeyRequest) *dnv1.UnrevokeKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.UnrevokeKeyRequest{}
	out.KeyId = src.KeyId
	return out
}

func toTestkitUnrevokeKeyRequest(src *dnv1.UnrevokeKeyRequest) *testkitv1.UnrevokeKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.UnrevokeKeyRequest{}
	out.KeyId = src.KeyId
	return out
}

func toDnUnrevokeKeyResponse(src *testkitv1.UnrevokeKeyResponse) *dnv1.UnrevokeKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.UnrevokeKeyResponse{}
	out.Key = toDnKeyInfo(src.Key)
	return out
}

func toTestkitUnrevokeKeyResponse(src *dnv1.UnrevokeKeyResponse) *testkitv1.UnrevokeKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.UnrevokeKeyResponse{}
	out.Key = toTestkitKeyInfo(src.Key)
	return out
}

func toDnUpdateKeyRequest(src *testkitv1.UpdateKeyRequest) *dnv1.UpdateKeyRequest {
	if src == nil {
		return nil
	}
	out := &dnv1.UpdateKeyRequest{}
	out.KeyId = src.KeyId
	if src.Label != nil {
		out.Label = src.Label
	}
	if src.Slots != nil {
		out.Slots = src.Slots
	}
	return out
}

func toTestkitUpdateKeyRequest(src *dnv1.UpdateKeyRequest) *testkitv1.UpdateKeyRequest {
	if src == nil {
		return nil
	}
	out := &testkitv1.UpdateKeyRequest{}
	out.KeyId = src.KeyId
	if src.Label != nil {
		out.Label = src.Label
	}
	if src.Slots != nil {
		out.Slots = src.Slots
	}
	return out
}

func toDnUpdateKeyResponse(src *testkitv1.UpdateKeyResponse) *dnv1.UpdateKeyResponse {
	if src == nil {
		return nil
	}
	out := &dnv1.UpdateKeyResponse{}
	out.Key = toDnKeyInfo(src.Key)
	return out
}

func toTestkitUpdateKeyResponse(src *dnv1.UpdateKeyResponse) *testkitv1.UpdateKeyResponse {
	if src == nil {
		return nil
	}
	out := &testkitv1.UpdateKeyResponse{}
	out.Key = toTestkitKeyInfo(src.Key)
	return out
}
